# QUIC.cloud credentials
QC_EMAIL="ufavisionseoteam@gmail.com"
QC_API_KEY="xxxxxxxxxxxx"

# cPanel Users (ว่าง = ทั้ง server)
CPANEL_USERS=""

# Telegram
TELEGRAM_BOT_TOKEN="8728146015:xxxx"
TELEGRAM_CHAT_ID="-5223351518"

# ตัวเลือก
BFM_TOGGLE="yes"       # ปิด/เปิด Bot Fight Mode อัตโนมัติ
LINK_RETRY=5           # retry link กี่ครั้ง
LINK_COOLDOWN=3        # delay ระหว่างเว็บ (วินาที)
